#+TITLE: tutorial-de-c
#+AUTHOR: Patricio Martínez
#+EMAIL: maxxcan@disroot.org

* Introducción

Este tutorial es una traducción del tutorial que podemos encontrar en [[https://www.tutorialspoint.com/cprogramming/index.htm][Tutorialspoint]]

* Resumen

C es un lenguaje de propósito general, un lenguaje de alto nivel que fue originalmente desarrollado por *Dennis M. Ritchie* para desarrollar el sistema operativo UNIX en los laboratorios Bell. C fue originalmente implementado para la computadora DEC PDP-11 en 1972. 

En 1979, Brian Kerninghan y Dennis Ritchie produjeron la primera descripción de C para el público, ahora conocido como el estándar K&R. 

El sistema operativo UNIX, el compilador de C y esencialmente todas las aplicaciones UNIX han sido escritas en C. C es un lenguaje ampliamente usado como lenguaje profesional por varias razones

+ Fácil de aprender
+ Lenguaje estructurado
+ Produce programas eficientes
+ Puede manejar actividades a bajo nivel
+ Se puede compilar para una amplia variedad de plataformas

** Hechos sobre C 

 + C fue inventado para escribir un sistema operativo llamado UNIX
 + C es un sucesor del lenguaje B el cual fue introducido sobre los tempranos 1970
 + El lenguaje fue formalizado en 1988 por el Instituto Nacional Americano de Estándares (ANSI)
 + El sistema operativo UNIX está totalmente escrito en C
 + A día de hoy C es el lenguaje más usado y popular como Lenguaje de Sistemas
 + Muchos de los estados de arte han sido implementados usando C
 + A día de hoy muchos de los populares Sistemas Operativos Linux o bases de datos como MySQL han sido escritos en C

** Por qué usar C

C fue inicialmente usado para el trabajo de desarrollo de sistemas, particularmente la programación de sistemas operativos. C fue adoptado como un lenguaje de desarrollo de sistemas porque producía código que corría casi tan rápido como código escrito en lenguaje ensamblador. Algunos ejemplos de uso de C podrían ser - 

+ Sistemas Operativos 
+ Compiladores de Lenguajes
+ Ensambladores
+ Editores de texto
+ Gestores de impresión
+ Controladores de Red
+ Programas modernos
+ Bases de datos
+ Lenguajes interpretados
+ Utilidades

** Programas en C

Un programa en C puede variar desde 3 líneas a millones de líneas y puede ser escrito en una o más ficheros de texto con la extensión *".c"*; por ejemplo, /hello.c/. Podemos usar "vi", "vim" o cualquier editor de texto para escribir tu programa C en un archivo.

Este tutorial asume que conoces como editar un fichero de texto y escribir código fuente en un archivo de programa. 


* C - Configurando el entorno

Si queremos configurar nuestro entorno de para programar en el lenguaje C, necesitamos las dos siguientes herramientas de software en nuestro computador; un Editor y el Compilador de C.

** Editor de texto

Será usado para escribir nuestro programa. Ejemplos de algunos editores incluyen Windows Notepad, OS Edit command, Brief, Epsilon, EMACS, y vim o vi. 

El nombre y la versión del editor de texto puede variar en diferentes sistemas operativos. Por ejemplo, Notepad será usado en Windows, y vim o vi puede ser usado en windows y también en Linux o UNIX.

Los archivos que creemos con el editor de texto son llamados archivos fuente y ellos contienen los códigos fuente. Los archivos fuente para los programas C son típicamente nombrados con la extensión *".c"*. 

Antes de empezar nuestro programa, tendremos que estar seguro que usamos un editor de texto con el cual tendremos suficiente experiencia para escribir programas, salvarlos, compilarlos y finalmente ejecutarlos.

** El compilador C

El código fuente escrito en el archivo fuente es la fuente humanamente leíble para nuestro programa. Pero necesita ser "compilado", en lenguaje máquina para que nuestra CPU puede realmente ejecutar el programa. 

El compilador compila el código fuente en el programa ejecutable final. El compilador más frecuentemente usado y de libre acceso es el compilador de GNU C/C++, en caso distinto tenemos los compiladores de HP o Solaris si tenemos los sistemas operativos respectivos. 

En la sección siguiente explicaremos como instalar el compilador GNU C/C++ en varios Sistemas Operativos. Mencionamos juntos C/C++ porque el compilador GNU Gcc funciona para ambos lenguajes. 

** Instalación en UNIX/Linux

Si estás usando *Linux o UNIX*, entonces comprobaremos si GCC está instalado en el sistema introduciendo el siguiente comando  - 

: $ gcc -v

Si el compilador  está instalado, entonces imprimirá el siguiente mensaje - 

#+BEGIN_SRC shell
Using built-in specs.
Target: i386-redhat-linux
Configured with: ../configure --prefix=/user ......
Thread model: posix
gcc version 4.1.2 200080704 (Red Hat 4.1.2-46)
#+END_SRC

Si GCC no está instalado, entonces tendremos que instalarlo por nosotros mismos usando las detalladas instrucciones disponibles en [[https://gcc.gnu.org/install/][la página de gcc]]. 

Este tutorial ha sido escrito basado en Linux y todos los ejemplos han sido compilados  en la distribución Cent OS del sistema Linux.

** Instalación en Mac OS

Si usas un Mac OS X, la forma más sencilla de obtener GCC es descargándose el entorno de desarrollo Xcode desde la página de Apple y seguir las instrucciones. Una vez hayas configurado Xcode, serás capaz de usar el Compilador GNU C/C++.

** Instalación en Windows

Para instalar GCC en Windows, se necesita instalar MinGW. Para instalar MinGW, es necesario ir a su [[http://www.mingw.org/][página]], y seguir el enlace a su página de descarga.

Mientras se instala Min GW, al mínimo, se debe instalar gcc-core, gcc-g++, binutils, y el MinGW runtime, pero se podrían instalar más cosas.

Añadiremos el subdirectorio *bin* de la instalación a la variable *PATH*, así como especificar las herramientas a usar. 

Después de que la instalación se haya completado, serás capaz de ejecutar gcc, g++, ranlib, diltool y varias otras herramientas de GNU en la línea de Comandos de Windows.

* C - Estructura del programa

Antes de que estudiemos los bloques básicos del programa C, echemos un ojo la estructura mínima de un programa en C que tomaremos de referencia en los siguientes capítulos. 

** Ejemplo - Hola Mundo - 

Un programa en C básicamente consiste de las siguientes partes - 

+ Comandos de preprocesado
+ Funciones
+ Variables
+ Declaraciones y expresiones
+ Comentarios

Echemos un vistazo a un simple código que puede dibujar las palabras "Hola Mundo" -  

#+BEGIN_SRC C
#include <stdio.h>

int main() {
/* mi primer programa en C*/
printf("Hola, Mundo! \n");

return 0
}
#+END_SRC

Veamos las  distintas partes del programa - 

+ La primera línea del programa #include<stdio.h> es  un comando preprocesador, el cual le dice al compilador de C incluir stdio.h antes de empezar a compilar. 

+ La siguiente línea /main()/ es la función principal donde la ejecución del programa comienza.

+ la siguiente línea /*..*/ será ignorada por el compilador y se usará para poner comentarios en el programa. Tales líneas son llamadas  comentarios en el programa.

+ La próxima línea /printf(...)/ es otra función disponible en C la cual causa que el mensaje "Hola Mundo!" sea mostrado en la pantalla. 

+ La siguiente línea *return 0*; termina la función main() y devuelve el valor 0.

** Compilando y ejecutando el programa C

Vamos a ver cómo salvar el código fuente en un archivo, como compilarlo y ejecutarlo. Siguiendo unos simples pasos - 

+ Abrir el editor de texto y añadir el código antes mencionado

+ Salvar el archivo como hola.c

+ Abrir una consola de comandos e ir al directorio donde se ha salvado el archivo

+ Escribir gcc hola.c y presionar intro para compilar el código

+ si no hay errores en el código, la línea de comandos generará un fichero ejecutable a.out

+ Ahora, escribimos a.out para ejecutar el programa

+ Veremos la salida "Hola Mundo" dibujado en la pantalla

: $ gcc hello.c
: $ ./a.out
: Hola Mundo!

* C - Sintáxis básica 

Hemos visto la estructura de un programa C, así que será fácil entender otros bloques de construcción del lenguaje C. 

** Tokens en C

Un programa en C consiste en varios tokens y un token puede ser una palabra clave, un identificador, una constante, una cadena de texto, o un símbolo. Por ejemplo, la siguiente declaración consiste de cinco tokens. - 

#+BEGIN_SRC C
printf("Hola Mundo! \n");
#+END_SRC

Los tokens individuales son - 

#+BEGIN_SRC C
printf
(
"Hola Mundo! \n"
)
;
#+END_SRC

** Punto y coma

En un programa C, el punto y coma es una declaración de fin. Eso es, cada declaración individual debe ser terminada con una punto y coma. Ello indica el final de una entidad lógica.

Aquí vemos dos declaraciones diferentes - 

#+BEGIN_SRC C
printf("Hola, Mundo! \n");
return 0;
#+END_SRC

** Comentarios

Los comentarios son como textos de ayuda  en el programa y son ignorados por el compilador. Empiezan con /* y terminan con */ tal como se muestra a continuación.

#+BEGIN_SRC C
/* mi primer programa en C */
#+END_SRC

No podemos tener comentarios dentro de comentarios y no pueden ocurrir con una cadena de caracteres.

** Identificadores 

Un identificador en C es un nombre usado para identificar una variable, función, o cualquier otro item definido por el usuario. Un identificador empiezar con unal letra de la A a la Z, mayúsculo o minúscula o un guíon bajo '_' seguido por cero o más letras, guiones bajos y dígitos (de 0 a 9).

C no permite caracteres de puntuación tales como @, $, y % en los identificadores. C es sensible a mayúsculas y minúsculas. Por lo que, Manpower y manpower son dos identificadores distintos en C. Aquí hay algunos ejemplos de identificadores aceptables - 

: mohd  zara abc move_name a_123
: myname50 _temp j a23b9 retVal

** Palabras clave

Las siguiente lista muestra las palabras reservadas en C. Esas palabras reservadas no deben ser usadas como constantes o variables o cualquier nombre de identificador. 


| auto     | else   | long     | switch   |
| break    | enum   | register | typedef  |
| case     | extern | return   | union    |
| char     | float  | short    | unsigned |
| const    | for    | signed   | void     |
| continue | goto   | sizeof   | volatile |
| default  | if     | static   | while    |
| do       | int    | struct   | _Packed  |
| double   |        |          |          |


** Espacios en blanco en C

Una línea conteniendo solo espacios en blanco, posiblemente con un comentario, es conocida como línea en blanco y el compilador de C la ignora.

Los espacios en blanco es el termino usado en C para describir espacio en blanco, tabulador, carácter de nueva línea y comentarios. Los espacios en blanco separa una parte de una declaración de otra y habilita al compilador a identificar donde un elemento en una declaración, tal como entero, finaliza y comienza el siguiente elemento.

Por lo tanto, en la siguiente declaración - 

: int edad;

debe haber al menos un espacio en blanco (normalmente un espacio) entre int y edad para que el compilador sea capaz de distinguirlos. Por otro lado, en la siguiente declaración - 

: frutas = manzanas + naranjas; //  obtener el total de frutas

Los espacios en blanco no son necesarios entre fruta y el símbolo =, o entre el = y las manzanas, además somos libres de incluir alguno más si deseamos mayor legibilidad. 

* C - Tipos de datos 

Los tipos de datos en C se refieren a un extensivo sistema usado para declarar variables o funciones de diferentes tipos. El tipo de variable determina cuanto espacio ocupará en memoria y como será el patrón de bits guardados interpretados. 

Los tipos en C puede ser clasificados de las siguiente manera - 

| Sr.No. | Tipos            | Descripción                                                                                             |
|      1 | Tipos básicos    | Son tipos aritméticos y clasificados en: enteros y comas flotante.                                      |
|      2 | Tipos enumerados | También son tipos aritméticos y son usados para definir variables que solo pueden ser valores discretos |
|      3 | El tipo vacío    | El tipo vacío especifica que no tienen ningún valor                                                     |
|      4 | Tipos derivados  | Incluyen punteros, arrays, estructuras, uniones y funciones                                             |


Los arrays y las estructuras son referidos colectivamente como tipos agregados. Los tipos funciones especifican un tipo que devuelve la función. Veremos los tipos básicos en la siguiente sección, donde como otros tipos serán cubiertos en sucesivos capítulos. 

** Tipos Enteros

La siguiente tabla proporciona los detalles de los tipos enteros estándar con sus tamaños y rangos de valor - 

| Tipo           | Tamaño      | Rango                                             |
|----------------+-------------+---------------------------------------------------|
| char           | 1 byte      | -128 a 127 o 0 a 255                              |
| unsigned char  | 1 byte      | 0 a 255                                           |
| signed char    | 1 byte      | -128 a 127                                        |
| int            | 2 o 4 bytes | -32,768 a 32,768 o -2,147,483,648 a 2,147,483,647 |
| unsigned it    | 2 o 4 bytes | 0 a 65,535 o 0 a 4,294,967,285                    |
| short          | 2 bytes     | -32,768 a 32,767                                  |
| unsigned short | 2 bytes     | 0 a 65,535                                        |
| long           | 8 bytes     | -9223372036854775808 a 9223372036854775807        |
| unsigned long  | 8 bytes     | 0 a 18446744073709551815                          |


Para obtener exactamente el tamaño de un tipo de variable en una plataforma en particular, podemos usar el operador *sizeof*. La expresión /sizeof(type)/ produce el tamaño del objeto o tipo en bytes. Veremos un ejemplo para obtener el tamaño de varios tipos en una computadora usando diferentes constantes definidos en el archivo limits.h


*** Demo 

#+BEGIN_SRC C
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <float.h>

int main(int argc, char** argv) {

printf("CHAR_BIT    :    %d\n", CHAR_BIT);
printf("CHAR_MAX    :    %d\n", CHAR_MAX);
printf("CHAR_MIN    :    %d\n", CHAR_MIN);
printf("INT_MAX     :    %d\n", INT_MAX);
printf("INT_MIN     :    %d\n", INT_MIN);
printf("LONG_MAX    :    %ld\n", (long) LONG_MAX);
printf("LONG_MIN    :    %ld\n", (long) LONG_MIN);
printf("SCHAR_MAX   :    %d\n", SCHAR_MAX);
printf("SCHAR_MIN   :    %d\n", SCHAR_MIN);
printf("SHRT_MAX    :    %d\n", SHRT_MAX);
printf("SHRT_MIN    :    %d\n", SHRT_MIN);
printf("UCHART_MAX  :    %d\n", UCHART_MAX);
printf("UINT_MAX    :    %u\n", (unsigned int) UINT_MAX);
printf("ULONG_MAX   :    %lu\n", (unsigned long) ULONG_MAX);
printf("USHRT_MAX   :    %d\n", (unsigned short) USHRT_MAX);

return 0;
}
#+END_SRC

Cuando compilemos y ejecutemos el programa, producirá el siguiente resultado en Linux - 

#+BEGIN_SRC 
CHAR_BIT    :   8
CHAR_MAX    :   127
CHAR_MIN    :   -128
INT_MAX     :   2147483647
INT_MIN     :   -2147483648
LONG_MAX    :   9223372036854775807
LONG_MIN    :   -9223372036854775808
SCHAR_MAX   :   127
SCHAR_MIN   :   -128
SHRT_MAX    :   32767
SHRT_MIN    :   -32768
UCHAR_MAX   :   255
UINT_MAX    :   4294967295
ULONG_MAX   :   18446744073709551615
USHRT_MAX   :   65535
#+END_SRC


** Tipos Coma flotante

La siguiente tabla proporciona los detalles de los tipos comas flotante estándar  con sus tamaños y los valores de sus rangos y su precisión - 

| Tipo        | Tamaño  | Rango                 | Precisión     |
|-------------+---------+-----------------------+---------------|
| float       | 4 byte  | 1.2E-38 a 3.4E+38     | 6 decimales   |
| double      | 8 byte  | 2.3E-308 a 1.7E+308   | 15 decimales  |
| long double | 10 byte | 3.4E-4932 a 1.1E+4932 | 19  decimales |

El fichero de cabecera float.h  define las macros que nos permite usar esas variables y otros detalles sobre la representación en binario de los números reales en nuestros programas. El siguiente ejemplo dibuja el espacio de guardado que toma los tipo coma flotante y su rango de valores. 

--Demo 

#+BEGIN_SRC C
#include <stdio.h>
#include <stdlib.h>
#include <limits.h> 
#include <float.h>

int main(int argc, char*** argv) {

printf("Espacio para el punto flotante: %d \n", sizeof(float));
printf("FLT_MAX     :   %g\n", (float) FLT_MAX);
printf("FLT_MIN     :   %g\n", (float) FLT_MIN);
printf("-FLT_MAX    :   %g\n", (float) -FLT_MAX);
printf("-FLT_MIN    :   %g\n", (float) -FLT_MIN);
printf("DBL_MAX     :   %g\n", (double) DBL_MAX);
printf("DBL_MIN     :   %g\n", (double) DBL_MIN);
printf("-DBL_MAX     :  %g\n", (double) -DBL_MAX);
printf("Valor de precisión: %d\n", FLT_DIG );

return 0;

}
#+END_SRC

Cuando ejecutemos el programa obtendremos el siguiente resultado en Linux - 

#+BEGIN_SRC
Espacio para el punto flotante: 4 
FLT_MAX      :   3.40282e+38
FLT_MIN      :   1.17549e-38
-FLT_MAX     :   -3.40282e+38
-FLT_MIN     :   -1.17549e-38
DBL_MAX      :   1.79769e+308
DBL_MIN      :   2.22507e-308
-DBL_MAX     :  -1.79769e+308
Valor de precisión: 6
#+END_SRC

** El tipo void

El tipo void especifica que ningún valor está disponible. Es usado en tres tipos de situaciones - 

+ La función devuelve void. 
  Hay varias funciones en C las cuales no devuelven ningún valor o que podemos decir que devuelvan void. Una función con ningún valor de retorno tiene el tipo de retorno como void. Por ejemplo *void exit(int status);* 

+ Argumento de función como void. 
Hay varias funciones en C las cuales no aceptan ningún parámetro. Una función sin ningún parámetro puede aceptar un void. Por ejemplo *int rand(void);* 

+ Punteros a void. 
Un puntero de tipo void representa la dirección de un objeto, pero no su tipo. Por ejemplo, una función de asiganción *void \*malloc( size_t size);* devuelve un puntero a void el cual puede ser referenciado a cualquier tipo de dato.
* C - Variables

Una variable no es nada más que un nombre que se le da a un área de almacenamiento que nuestro programa puede manipular. Cada variable en C tiene un tipo específico, el cual determina el tamaño la capa de la variable de memoria; el ragon de valores que puede ser guardado en esa memoria; y el conjunto de operaciones que pueden ser aplicadas a la variable.

El nombre de una variable puede estar compuesto de letras, dígitos, y guiones bajos. Deben empezar por una letra o un guión bajo. C distingue entre letras mayúsculas y minúsculas ya que C es case-sensitivo. Basandose en los tipos básicos explicados en el capítulo anterior, veremos los siguientes tipos de variables. 

| Nº | Tipo     | Descripción                                          |
|----+----------+------------------------------------------------------|
|  1 | Caracter | Típicamente un octeto (un byte). Es un tipo entero   |
|  2 | Entero   | El tipo más natural de tamaño entero para la máquina |
|  3 | Flotante | Un simple precisión flotante Valor                   |
|  4 | double   | Una doble precisión flotante valor                   |
|  5 | void     | Representa la ausencia de tipo                       |

El lenguaje C también permite definir otros varios tipos de variables, las cuales serán cubiertas en los subsecuentes capítulos como Enumeración, Punteros, Arrays, Estructuras, Uniones, etc. Por este capítulo, vamos a estudiar solo los tipos básicos.

** Definición de variable en C 

Una definición de variable le dice al compilador donde y cuanto de grande es el almacenamiento por crear para la variable. La definición de variable especifica un tipo de dato y contiene una lista de uno o más variables de esos tipos, como sigue -- 

: tipo lista_de_variables;

Aquí *tipo* debe ser un dato C válido incluyendo char, w_char, int, float, double, bool, o cualquier tipo de objeto definido por el usuario; una *lista_de_variables* que consistirá en uno o más nombres identificadores separados por comas. Algunas declaraciones válidas son mostradas aquí - 


#+BEGIN_SRC C
int i, j, k;
char c, ch;
float f, salario;
double d;

#+END_SRC

En la primera línea declaramos las variables i,j y k; las cuales le damos las instrucciones al compilador el crear variables llamadas i,j y k del tipo entero.

Las variables pueden ser inicializadas (asignándoles un valor inicial) en esa declaración.  La inicialización consiste en un signo igual seguido de una expresión constante tal como sigue -

: tipo nombre_variable = valor;

Algunos ejemplos serían --

#+BEGIN_SRC C

extern int d = 3, f = 5;  // declaración de d y f.
int d = 3, f = 5;  // definición e inicialización de d y f.
byte z = 22;   // definición e inicialización de z.
char x = 'x';   // la variable x tiene el valor 'x'.

#+END_SRC

Para definir sin inicializar: las variables con almacenamiento de duración estático son implícitamente inicializados con NULL (todos los bytes tienen el valor 0); el valor inicial de todos las otras variables son indefinidos.

** Declaración de variables en C 

Una declaración de variable proporciona garantía al compilador de que existe una variable con el tipo dado y el nombre así que el compilador puede proceder más rápido a la compilación sin requerir el completo detalle sobre la variable. Una definición de variable tiene su significado en el momento de compilación solo, el compilador necesita una definición de variable en el momento del linkado del programa. 

Una declaración de variable es muy útil cuando usamos múltiples archivos y definimos nuestra variable en uno de los archivos el cual debe ser accesible en el momento del linkado de el programa. Usaremos la palabra clave *extern* para declarar una variable en un lugar. Además podemos declarar una variable muchas veces en nuestro programa C, ello puede ser definido solo una vez en un archivo, una función o un bloque de código.

*** Ejemplo   

Veamos el siguiente ejemplo, donde las variables han sido declaradas al principio, pero han sido definidas e inicializadas dentro de la función principal - 

#+BEGIN_SRC C
#+inclue <stdio.h>

// declaración de variables
extern int a, b;
extern int c;
extern float f;

int main() {

/* definición de variables */
int a, b;
int c;
float f;

/* verdadera inicialización */
a = 10;
b = 20;

c = a + b;
printf("el valor de c : %d \n", c);

f = 70.0/3.0;
printf("el valor de f : %f \n", f);

return 0;

}

#+END_SRC

Cuando compilemos y ejecutemos el código anterior, se producirá el siguiente resultado - 

: el valor de c : 30
: el valor de f : 23.3333334

El mismo concepto aplicado en las declaraciones de funciones donde proveeremos el nombre de una función al mismo tiempo que su declaración y su verdadera definición puede ser dada en cualquier sitio más. Por ejemplo - 

#+BEGIN_SRC C
// declaración de función
int func();

int main() {

//llamada a la función
int i = func()
}

//definición de función
int func(){
return 0;
}

#+END_SRC

Valor-L y Valor-R en C 

Hay dos tipos de expresiones en C - 

- l-valor - Las expresiones que se refieren a la posición de memoria son llamadas expresiones "l-valor". Una l-valor puede aparecer tanto como mano izquierda o mano derecha de una asignación.

- r-valor - El termino r-valor se refiere a un valor de datos que es guardado en una dirección de memoria. Un r-valor es una expresión que no puede tener un valor asignado a ello lo cual significa que un r-valor puede aparecer a la derecha pero no a la izquierda de una asignación.

Las variables son l-valores y así pueden aparecer en el lado izquierdo de una asignación. Los literales numéricos son r-valores y así ellos no deben ser asignados y no pueden aparecer en el lado izquierdo de una asignación. Echemos un vistazo a una declaración válida y a otra inválida.

: int g = 20; //declaración válida
: 10 = 20 // declaración inválida; generará un error en tiempo de compilación


